version: 2
jobs:
  lint:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - terraform validate

  plan:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - terraform plan -out=plan.tfplan
      - persist_to_workspace:
          root: .
          paths: plan.tfplan

  apply:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - attach_workspace:
          at: .
      - terraform apply plan.tfplan

workflows:
  version: 2
  commit:
    - lint
    - plan:
        requires:
          - lint
    - hold:
        type: approval
        requires:
          - plan

    - apply:
        requires:
          - hold
