version: 2
jobs:
  plan:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run: terraform init
      - run: terraform validate
      - run: terraform plan -out=plan.tfplan
      - persist_to_workspace:
          root: .
          paths:
            - plan.tfplan
            - .terraform

  apply:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: terraform apply plan.tfplan

workflows:
  version: 2
  commit:
    jobs:
      - plan
      - apply:
          requires:
            - plan
          filters:
            branches:
              only:
                - master
