
version: 2
jobs:
  lint:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run: terraform validate

  plan:
    docker:
      - image: hashicorp/terraform:light
    environment:
      TF_WORKSPACE: production
    steps:
      - checkout
      - run: terraform init
      - run: terraform select $TF_WORKSPACE
      - run: terraform plan -out=plan.tfplan
      - persist_to_workspace:
          root: .
          paths:
            - plan.tfplan
            - .terraform

  apply:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: terraform apply plan.tfplan

workflows:
  version: 2
  commit:
    jobs:
      - lint
      - plan:
          requires:
            - lint

      - hold:
          type: approval
          requires:
            - plan
          filters:
            branches:
              only:
                - master

      - apply:
          requires:
            - hold
